Add user and developer guide
AY2122S2-CS2103-W16-4/tp pull request #34
Opened 2022-03-02 13:47 UTC by hsiaojietng

Update the guides as project goes along

2022-03-02 15:04 UTC, waffledood requested changes

2022-03-03 04:43 UTC, hsiaojietng commented on docs/DeveloperGuide.md
> +![Untitled](Developer%20%2001421/Untitled.png)
I have updated with the correct hyperlink. Should work now on the developer guide. Also, I have categorized images by creating directories like 'user-guide', 'developer-guide' and 'team' should there be any other images to add in the guides or the team's page.

2022-03-03 08:25 UTC, waffledood commented on docs/DeveloperGuide.md
> +![Untitled](Developer%20%2001421/Untitled.png)
looks good, thanks Jiet! 👍

2022-03-03 08:26 UTC, waffledood approved these changes

2022-03-03 08:26 UTC, waffledood commented
LGTM! 🚀

2022-03-03 10:07 UTC, merged