Minor changes to pass week-7 checks
AY2122S2-CS2103-W16-4/tp pull request #39
Opened 2022-03-03 17:59 UTC by cindyangXQ

2022-03-03 18:18 UTC, Ashuh commented on docs/AboutUs.md
> +<img src="images/hsiaojietng.jpeg" width="200px">
File extension should be `.png` as described [here](https://nus-cs2103-ay2122s2.github.io/website/schedule/week7/project.html#2-update-project-website-aboutus-readme).

2022-03-03 18:37 UTC, Ashuh requested changes
Looks good but Jiet's profile picture extension needs to be changed.

2022-03-04 02:40 UTC, waffledood commented
I've converted Jiet's picture to `.png` format, available here, you can right click & choose "Download" 
![hsiaojietng](https://user-images.githubusercontent.com/59903913/156688761-da39569d-dbdc-4feb-9e47-dc769c3480e0.png)

2022-03-04 04:44 UTC, waffledood approved these changes
LGTM! 👍

2022-03-04 05:10 UTC, Ashuh approved these changes
LGTM

2022-03-04 05:11 UTC, merged